-- init.lua
require("netzego/options")
require("netzego/plugins")
require("netzego/keymaps")
-- Plugins
require("netzego/pepe")
require("netzego/lsp")
require("netzego/lsp_sumneko")
require("netzego/lsp_tsserver")
require("netzego/null_lsp")
require("netzego/treesitter")
require("netzego/telescope")
require("netzego/lualine")
require("netzego/gitsigns")
require("netzego/cmp")
require("netzego/snippy")
require("netzego/comment")
-- require("netzego/py_lsp")
