-- 3rd party plugins highlights
local base = require("pepe.base")
local styles = require("pepe.settings").styles
local colors = require("pepe.colors")

local plugins = {
  -- netrw
  netrwDir = base.PepeAqua,
  netrwClassify = base.PepeAqua,
  netrwLink = base.PepeGray,
  netrwSymLink = base.PepeFg1,
  netrwExe = base.PepeYellow,
  netrwComment = base.PepeGray,
  netrwList = base.PepeBlue,
  netrwHelpCmd = base.PepeAqua,
  netrwCmdSep = base.PepeFg3,
  netrwVersion = base.PepeGreen,
  -- nvim-treesitter
  TSNone = {},
  TSError = {},
  TSTitle = base.Title,
  TSLiteral = base.String,
  TSURI = base.Underlined,
  TSVariable = base.PepeFg1,
  TSPunctDelimiter = base.Delimiter,
  TSPunctBracket = base.Delimiter,
  TSPunctSpecial = base.Delimiter,
  TSConstant = base.Constant,
  TSConstBuiltin = base.Special,
  TSConstMacro = base.Define,
  TSString = base.String,
  TSStringRegex = base.String,
  TSStringEscape = base.SpecialChar,
  TSCharacter = base.Character,
  TSNumber = base.Number,
  TSBoolean = base.Boolean,
  TSFloat = base.Float,
  TSFunction = base.Function,
  TSFuncBuiltin = base.Special,
  TSFuncMacro = base.Macro,
  TSParameter = base.Identifier,
  TSParameterReference = "TSParameter",
  TSMethod = base.Function,
  TSField = base.Identifier,
  TSProperty = base.Identifier,
  TSConstructor = base.Special,
  TSAnnotation = base.PreProc,
  TSAttribute = base.PreProc,
  TSNamespace = base.Include,
  TSConditional = base.Conditional,
  TSRepeat = base.Repeat,
  TSLabel = base.Label,
  TSOperator = base.Operator,
  TSKeyword = base.Keyword,
  TSKeywordFunction = base.Keyword,
  TSKeywordOperator = base.PepeRed,
  TSException = base.Exception,
  TSType = base.Type,
  TSTypeBuiltin = base.Type,
  TSInclude = base.Include,
  TSVariableBuiltin = base.Special,
  TSText = "TSNone",
  TSStrong = { gui = styles.bold },
  TSEmphasis = { gui = styles.italic_strings },
  TSUnderline = { gui = styles.underline },
  TSComment = base.Comment,
  TSStructure = base.PepeOrange,
  TSTag = base.PepeOrange,
  TSTagDelimiter = base.PepeGreen,

  -- telescope.nvim
  TelescopeSelection = base.PepeOrangeBold,
  TelescopeSlectionCaret = base.PepeRed,
  TelescopeMultiSelection = base.PepeGray,
  TelescopeNormal = base.PepeFg1,
  TelescopeBorder = "TelescopeNormal",
  TelescopePromptBorder = "TelescopeNormal",
  TelescopeResultsBorder = "TelescopeNormal",
  TelescopePreviewBorder = "TelescopeNormal",
  TelescopeMatching = base.PepeBlue,
  TelescopePromptPrefix = base.PepeRed,
  TelescopePrompt = "TelescopeNormal",
  -- lspsaga.nvim
  LspSagaDiagnosticBorder = base.NormalNC,
  LspSagaDiagnosticHeader = base.PepeRed,
  LspSagaDiagnosticTruncateLine = base.NormalNC,
  LspFloatWinBorder = base.NormalNC,
  LspSagaBorderTitle = base.Title,
  TargetWord = base.Error,
  ReferencesCount = base.Title,
  ReferencesIcon = base.Special,
  DefinitionCount = base.Title,
  TargetFileName = base.Comment,
  DefinitionIcon = base.Special,
  ProviderTruncateLine = base.NormalNC,
  SagaShadow = base.PepeBg0,
  LspSagaFinderSelection = base.Search,
  DiagnosticTruncateLine = base.NormalNC,
  DiagnosticWarning = base.DiagnosticWarn,
  DiagnosticInformation = base.DiagnosticInfo,
  DefinitionPreviewTitle = base.Title,
  LspSagaShTruncateLine = base.NormalNC,
  LspSagaDocTruncateLine = base.NormalNC,
  LineDiagTuncateLine = base.NormalNC,
  LspSagaCodeActionTitle = base.Title,
  LspSagaCodeActionTruncateLine = base.NormalNC,
  LspSagaCodeActionContent = base.Normal,
  LspSagaRenamePromptPrefix = base.PepeFg2,
  LspSagaRenameBorder = { gui = styles.bold },
  LspSagaHoverBorder = { gui = styles.bold },
  LspSagaSignatureHelpBorder = { gui = styles.bold },
  LspSagaCodeActionBorder = { gui = styles.bold },
  LspSagaAutoPreview = {},
  LspSagaDefPreviewBorder = { gui = styles.bold },
  LspLinesDiagBorder = { gui = styles.bold },
  -- vim-startify
  StartifyBracket = base.PepeFg3,
  StartifyFile = base.PepeFg1,
  StartifyNumber = base.PepeBlue,
  StartifyPath = base.PepeGray,
  StartifySlash = base.PepeGray,
  StartifySection = base.PepeYellow,
  StartifySpecial = base.PepeBg2,
  StartifyHeader = base.PepeOrange,
  StartifyFooter = base.PepeBg2,
  StartifyVar = "StartifyPath",
  StartifySelect = base.Title,
  -- vim-signify
  SignifySignAdd = base.PepeGreenSign,
  SignifySignChange = base.PepeAquaSign,
  SignifySignDelete = base.PepeRedSign,
  -- syntastic
  SyntasticError = base.PepeRedUnderline,
  SyntasticWarning = base.PepeYellowUnderline,
  SyntasticErrorSign = base.PepeRedSign,
  SyntasticWarningSign = base.PepeYellowSign,
  -- termdebug
  debugPC = { bg = colors.faded_blue },
  debugBreakpoint = base.PepeRedSign,
  -- vim-dirvish
  DirvishPathTail = base.PepeAqua,
  DirvishArg = base.PepeYellow,
  -- nerdtree
  NERDTreeDir = base.PepeAqua,
  NERDTreeDirSlash = base.PepeAqua,
  NERDTreeOpenable = base.PepeOrange,
  NERDTreeClosable = base.PepeOrange,
  NERDTreeFile = base.PepeFg1,
  NERDTreeExecFile = base.PepeYellow,
  NERDTreeUp = base.PepeGray,
  NERDTreeCWD = base.PepeGreen,
  NERDTreeHelp = base.PepeFg1,
  NERDTreeToggleOn = base.PepeGreen,
  NERDTreeToggleOff = base.PepeRed,
  -- coc.nvim
  CocErrorSign = base.PepeRedSign,
  CocWarningSign = base.PepeOrangeSign,
  CocInfoSign = base.PepeBlueSign,
  CocHintSign = base.PepeAquaSign,
  CocErrorFloat = base.PepeRed,
  CocWarningFloat = base.PepeOrange,
  CocInfoFloat = base.PepeBlue,
  CocHintFloat = base.PepeAqua,
  CocDiagnosticsError = base.PepeRed,
  CocDiagnosticsWarning = base.PepeOrange,
  CocDiagnosticsInfo = base.PepeBlue,
  CocDiagnosticsHint = base.PepeAqua,
  CocSelectedText = base.PepeRed,
  CocCodeLens = base.PepeGray,
  CocErrorHighlight = base.PepeRedUnderline,
  CocWarningHighlight = base.PepeOrangeUnderline,
  CocInfoHighlight = base.PepeBlueUnderline,
  CocHintHighlight = base.PepeAquaUnderline,
  -- ale.vim
  ALEError = base.PepeRedUnderline,
  ALEWarning = base.PepeYellowUnderline,
  ALEInfo = base.PepeBlueUnderline,
  ALEErrorSign = base.PepeRedSign,
  ALEWarningSign = base.PepeYellowSign,
  ALEInfoSign = base.PepeBlueSign,
  ALEVirtualTextError = base.PepeRed,
  ALEVirtualTextWarning = base.PepeYellow,
  ALEVirtualTextInfo = base.PepeBlue,
  -- vim-buftabline
  BufTabLineCurrent = base.TabLineSel,
  BufTabLineActive = base.PmenuSel,
  BufTabLineHidden = base.TabLine,
  BufTabLineFill = base.TabLineFill,
  BufTabLineModifiedCurrent = "BufTabLineCurrent",
  BufTabLineModifiedActive = "BufTabLineActive",
  BufTabLineModifiedHidden = "BufTabLineHidden",
  -- ctrlP
  CtrlPMatch = base.Identifier,
  CtrlPNoEntries = base.Error,
  CtrlPPrtBase = base.Comment,
  CtrlPPrtCursor = base.Constant,
  CtrlPLinePre = { fg = base.PepeBg2.fg },
  CtrlPMode1 = base.Character,
  CtrlPMode2 = base.LineNr,
  CtrlPStats = base.Function,
  -- fzf.vim
  Fzf1 = { fg = base.PepeBlue.fg, bg = base.PepeBg1.fg },
  Fzf2 = { fg = base.PepeOrange.fg, bg = base.PepeBg1.fg },
  Fzf3 = { fg = base.PepeFg4.fg, bg = base.PepeBg1.fg },
  ShowMarksHLl = base.PepeBlueSign,
  ShowMarksHLu = base.PepeBlueSign,
  ShowMarksHLo = base.PepeBlueSign,
  ShowMarksHLm = base.PepeBlueSign,
  -- git-gutter
  GitGutterAdd = base.PepeGreenSign,
  GitGutterChange = base.PepeAquaSign,
  GitGutterDelete = base.PepeRedSign,
  GitGutterChangeDelete = base.PepeAquaSign,
  -- gitsigns.nvim
  GitSignsAdd = base.PepeGreenSign,
  GitSignsChange = base.PepeAquaSign,
  GitSignsDelete = base.PepeRedSign,
  GitSignsCurrentLineBlame = base.NonText,
  -- nvim-cmp
  CmpItemAbbr = base.PepeFg0,
  CmpItemAbbrDeprecated = base.PepeFg0,
  CmpItemAbbrMatch = base.PepeBlue,
  CmpItemAbbrMatchFuzzy = { gui = styles.underline, fg = base.PepeAqua.fg },
  CmpItemKind = base.PepeOrange,
  CmpItemKindClass = base.PepeGreen,
  CmpItemKindConstructor = base.PepeGreen,
  CmpItemKindField = base.PepeAqua,
  CmpItemKindFile = base.PepeOrange,
  CmpItemKindFolder = base.PepeOrange,
  CmpItemKindFunction = base.PepePurple,
  CmpItemKindInterface = base.PepeGreen,
  CmpItemKindKeyword = base.Keyword,
  CmpItemKindMethod = base.PepePurple,
  CmpItemKindSnippet = base.PepeYellow,
  CmpItemKindText = base.PepeFg0,
  CmpItemKindValue = base.PepeOrange,
  CmpItemKindVariable = base.PepeBlue,
  CmpItemMenu = base.PepeGray,
  -- LSP
  LspCodeLens = base.PepeGray,
  LspReferenceRead = { bg = base.PepeBg2.fg, gui = styles.underline },
  LspReferenceText = { bg = base.PepeBg2.fg, gui = styles.underline },
  LspReferenceWrite = { bg = base.PepeBg2.fg, gui = styles.underline },
  -- Diagnostic
  DiagnosticError = base.PepeRed,
  DiagnosticSignError = base.PepeRedSign,
  DiagnosticUnderlineError = base.PepeRedUnderline,
  DiagnosticWarn = base.PepeYellow,
  DiagnosticSignWarn = base.PepeYellowSign,
  DiagnosticUnderlineWarn = base.PepeYellowUnderline,
  DiagnosticInfo = base.PepeBlue,
  DiagnosticSignInfo = base.PepeBlueSign,
  DiagnosticUnderlineInfo = base.PepeBlueUnderline,
  DiagnosticHint = base.PepeAqua,
  DiagnosticSignHint = base.PepeAquaSign,
  DiagnosticUnderlineHint = base.PepeAquaUnderline,
  DiagnosticFloatingError = base.PepeRed,
  DiagnosticFloatingWarn = base.PepeOrange,
  DiagnosticFloatingInfo = base.PepeBlue,
  DiagnosticFloatingHint = base.PepeAqua,
  DiagnosticVirtualTextError = base.PepeRed,
  DiagnosticVirtualTextWarn = base.PepeYellow,
  DiagnosticVirtualTextInfo = base.PepeBlue,
  DiagnosticVirtualTextHint = base.PepeAqua,
  -- mail.vim
  mailQuoted1 = base.PepeAqua,
  mailQuoted2 = base.PepePurple,
  mailQuoted3 = base.PepeYellow,
  mailQuoted4 = base.PepeGreen,
  mailQuoted5 = base.PepeRed,
  mailQuoted6 = base.PepeOrange,
  mailSignature = base.Comment,
}

return plugins
